### ISSUE TITLE
Not colorizing in workspace

### ISSUE THREAD

**Issue by xErik** [egorovsa/vscode-folder-colorizer#1]
Working with the latest version if VS Code (1.84.1), the folders are not colored.  

See attachment, the folder `lib` should be colored red.

Please let me know, if I can provider additional information to sort this out.

![image](https://github.com/egorovsa/vscode-folder-colorizer/assets/1338567/496bb7c2-13d8-4160-bd8c-1adb693da126)

**Comment by egorovsa** [comment]
@xErik  Hi. Thanks. I will check it and let you know soon.
It has' not worked at all for you or you faced this only after vscode updates??

**Comment by egorovsa** [comment]
Ok. Seems I've got it...Will fix it soon. That's windows paths...

**Comment by egorovsa** [comment]
Hey . Thanks for the issue . Now this plugin adapter for windows as well ;)
Please update it up to v 0.0.7
Also it will probably necessary to erase settings.json pathColor  config

**Comment by egorovsa** [comment]
I've just checked it again in Windows VsCode.
I also switched off all other plugins and everything is working perfect.
BTW . thanks for the link, I was trying to find this many time, did not find and then I implemented it myself. 

I do not think that  VS Code changed something because I installed the last api version so it should work perfect.

**Comment by egorovsa** [comment]
Thanks anyway. I will try to ask my friends to check it on windows as well. If I find out something I will let you know .

**Comment by egorovsa** [comment]
BTW , sometimes it requires to restart VSCODE and the works well. 
just Ctrl + Shift + P 
then 
"Reload window" command

**Comment by ubless607** [comment]
> BTW , sometimes it requires to restart VSCODE and the works well. just Ctrl + Shift + P then "Reload window" command

This works. Can you write this down on README.MD?
