### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by the-moog** [egorovsa/vscode-folder-colorizer#2]
Great addon, thanks. Should be in the core VSCode!
Typo or spelling error: v0.0.7

On the bottom of the right click in Explorer context menu, "Budge" -> "Badge"

(British??) English: "Budge" == To attempt to move something that is reluctant to move; e.g. "It's stuck, I tried to move it but it won't budge"

English: "Badge" == Some sort of visible label; e.g. "Look at my badge"

**Comment by egorovsa** [comment]
@the-moog  Thanks a lot for your feedback! I do appreciate it. 

Hah. My fault! 
English is not my mother thong, so It can happens )) I will fix it soon!
Thanks again,

**Comment by egorovsa** [comment]
v.0.0.8 is ready !
thanks
