### ISSUE TITLE
Suggestion: Visually pleasing and easier to identify Badges

### ISSUE THREAD

**Issue by the-moog** [egorovsa/vscode-folder-colorizer#3]
In addition to the current possibility of 1..2 letters it would be really cool to be able to have support for Emoji and/or UNICODE characters, e.g. `:smile:` == 😄 or `~u5408` == 🈴[^nb]

Here (for example) using the first of the two characters (here `:` and `~` are used) as an escape to allow input other than two typed characters.

[^nb]:  Footnote:  In an attempt to use a contextually appropriate UNICODE, I chose this symbol. I hope this means "Combine" - Apologies if this is not an apropriate character as I do not read Chinese, this character is from Google Translate.

**Comment by egorovsa** [comment]
This is a perfect IDEA. I will consider this. I've checked and it works cool )

**Comment by egorovsa** [comment]
Version 0.1.0 is available.. 
"Set EMOJI badge"  now will enable you a big choice of all emoji .
