### ISSUE TITLE
Choice of custom colors

### ISSUE THREAD

**Issue by NabiKAZ** [egorovsa/vscode-folder-colorizer#6]
Thank you for your good plugin.
I need to enter my custom color.
I tested this but it didn't work:
```
  "settings": {
  "folder-color.pathColors": [
  {
  "folderPath": "folder\\",
  "color": "#ff0000"
  }
```

**Comment by egorovsa** [comment]
That's impossible to use your custom color due to VSCode API.
I have just released a new version and color pallet is also updated.
I hope you will find a color you prefer.
