### ISSUE TITLE
Color multiple files at once

### ISSUE THREAD

**Issue by mqnc** [egorovsa/vscode-folder-colorizer#8]
When I select multiple files in the explorer view using shift or ctrl, only the last selected gets colorized.

**Comment by egorovsa** [comment]
Hello. Yes, that's confirmed. I will try to come up with something.

**Comment by egorovsa** [comment]
Fixed, now you apply color for multiple folders or files

**Comment by mqnc** [comment]
Works, awesome! Thanks!
