### ISSUE TITLE
[bug] colors are not applied to tree items in the Source Control view

### ISSUE THREAD

**Issue by OmarTawfik** [egorovsa/vscode-folder-colorizer#9]
Thank you for the very useful extension.

With this configuration:

```json
  "folder-color.pathColors": [
    {
      "folderPath": "generated",
      "color": "foldercolorizer.purple",
      "badge": "G"
    }
  ]
```

In the Explorer viewer, both folders and individual files under them are colorized correctly. They also have the colorized badge:

<img width="185" alt="image" src="https://github.com/user-attachments/assets/249da416-bff7-497f-9446-623a45d718fc">

But for the Source control view, they only have the badge (uncolorized), and neither folders nor files are colorized correctly:

<img width="225" alt="image" src="https://github.com/user-attachments/assets/8207bd2a-2e81-4439-a940-7e708ab9300b">

I wonder if there is a way to make them consistent?

**Comment by egorovsa** [comment]
Yes. You are right and unfortunately this is a bug of VSCode color API . 
Seems Source control view doest not support it. I will check this out anyway and will let you know.
